export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const CHECK_LOGIN_STATUS = 'CHECK_LOGIN_STATUS';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const GET_ITEM_BY_CATEGORY = 'GET_ITEM_BY_CATEGORY';
