export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const SELECT_TAB = 'SELECT_TAB';
export const CHECK_LOGIN_STATUS = 'CHECK_LOGIN_STATUS';
export const CHANGE_LOGIN_STATUS = 'CHANGE_LOGIN_STATUS';
export const SET_SEARCH_KEYWORD = 'SET_SEARCH_KEYWORD';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const GET_ITEM_BY_CATEGORY = 'GET_ITEM_BY_CATEGORY';
export const CHANGE_ROUTER = 'CHANGE_ROUTER';
